language: node_js
node_js:
  - 18
# addons:
#   packages:
#     - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script: -eslint 'src/**'
  - npm run test:ci
  - npm run test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: nomenoheroku
  skip_cleanup: true
notifications:
  email: false
